# Generated by Django 3.2.4 on 2021-06-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(db_index=True, unique=True)),
                ('short_url', models.URLField(db_index=True, max_length=7, unique=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
